#This Pipeline will create a image and push to the AWS ECR


trigger:
 - master

#Declaring the Variables

variables:
 awsServiceConnection: 'AWS'
 ecrRepository: 'test_mvc'
 dockerFilePath: 'Test_MVC/Dockerfile'
 Tag: '$(Build.BuildId)'
 vmImageName: 'ubuntu latest'

resources:
 - repo: self

stages:
  - stage: Build
    displayName: Build Dotnet Application
    jobs:
      - job: Build
        displayName: Build Dotnet Test_mvc Application
        pool:
          vmImage: $(vmImageName)
        steps:
        - task: AWSCLI@1
          displayName: Login to the AWS ECR
          inputs:
            awsCredentials: 'AWS'
            regionName: 'ap-south-1'
            awsCommand: 'aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 565601886809.dkr.ecr.ap-south-1.amazonaws.com'
            
